name: Firebolt Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MODULAR_HOME: "/home/runner/.modular"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - uses: prefix-dev/setup-pixi@v0.8.8
      with:
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    - name: checks
      run: pixi run fmt
    - name: tests
      run: pixi run test